# Generated by Django 5.2.2 on 2025-06-08 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('bkash', 'BKash'), ('nagad', 'Nagad'), ('rocket', 'Rocket'), ('cash', 'Cash')], max_length=20),
        ),
    ]
