# Generated by Django 5.2.2 on 2025-06-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_job_assigned_worker_alter_user_is_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='status',
            field=models.CharField(choices=[('selected', 'Selected'), ('ignored', 'Ignored'), ('not_selected', 'Not Selected')], default='not_selected', max_length=20),
        ),
    ]
