# Generated by Django 5.2.2 on 2025-06-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_bid_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AddField(
            model_name='worker',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic_worker/'),
        ),
    ]
