# Generated by Django 5.2.2 on 2025-06-17 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_user_profile_picture_worker_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='WorkerWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('worker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.worker')),
            ],
        ),
    ]
